name: Build and Deploy on Main

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          cache: 'maven'
      - name: Permitir execução do mvnw
        run: chmod +x ./mvnw
      - name: Build e Testes
        run: ./mvnw -B clean verify --no-transfer-progress
      - name: Build Docker image
        run: docker build -t spring-6-gateway:latest .
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create tag (minor por padrão)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
