name: PR Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          cache: 'maven'

      - name: Permitir execução do mvnw
        run: chmod +x ./mvnw

      - name: Build e Testes
        run: ./mvnw -B clean verify --no-transfer-progress

      - name: Cobertura de Testes
        run: ./mvnw jacoco:report

      # Exemplo de publicação de cobertura (opcional, se usar Codecov ou Coveralls)
      # - name: Upload cobertura para Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./target/site/jacoco/jacoco.xml
